---
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  annotations: {}
  name: "foo"
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: "foo"
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: "foo"
      annotations: {}
    spec:
      terminationGracePeriodSeconds: 30
      nodeSelector: {}
      containers:
      - name: "foo"
        image: "busybox:latest"
        command:
        - "sleep"
        args:
        - "325435346536"
        imagePullPolicy: "IfNotPresent"
---
apiVersion: v1
kind: Service
metadata:
  name: foo
spec:
  selector:
    app: foo 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: foo-https
spec:
  selector:
    app: foo
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cmfoo
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"
  #
  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
---
apiVersion: v1
kind: Secret
metadata:
  name: secretfoo2
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
---
apiVersion: v1
kind: Secret
metadata:
  name: secretfoo
type: Opaque
data:
  username: YWRtaW4=
stringData:
  username: administrator
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cmfoo-two
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"
  #
  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5M
---
apiVersion: v1
kind: Secret
metadata:
  name: secretfoo-two
type: Opaque
data:
  username: YWRtaW4=
stringData:
  username: administrator
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cmfoo-three
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"
  #
  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foo-two
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5M
