---
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  annotations: {}
  name: "nginx-test"
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: "nginx-test"
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: "nginx-test"
      annotations: {}
    spec:
      terminationGracePeriodSeconds: 30
      nodeSelector: {}
      containers:
      - name: "foo"
        image: "nginx:latest"
        command:
        - "sleep"
        args:
        - "325435346536"
        imagePullPolicy: "IfNotPresent"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test
spec:
  type: NodePort
  selector:
    app: nginx-test 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test
spec:
  selector:
    app: foo
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
